### ISSUE TITLE
Use menhir-based parser instead of camlp4o

### ISSUE THREAD

**Issue by seliopou** [yoriyuki/Camomile#16]
The library uses camlp4o to parse locale definitions, which is a hinderance to both adoption (see tategakibunko/jingoo#19) as well as future maintenance. The parser should be ported to menhir or some such other parser library to break the dependency with camlp4o.

**Comment by rgrinberg** [comment]
+1, we should absolutely get rid of camlp4 where possible.

@michipili definitely a milestone before 1.0 IMO

**Comment by seliopou** [comment]
The grammar that the parser implements is documented [here](http://source.icu-project.org/repos/icu/icuhtml/trunk/design/bnf_rb.txt).

It took forever to find it. Enterprise software is terrifying.

**Comment by michipili** [comment]
@rgrinberg Agreed! #12.

**Comment by rgrinberg** [comment]
I have a branch (on top of #22) that replaces the camlp4 lexer with with the same lexer but without the syntax extension. It would still be nice to have a proper menhir based parser, but i think that should be enough to solve this problem for the medium term.

**Comment by rgrinberg** [comment]
We aren't using camlp4 anymore.
