### ISSUE TITLE
compilation of zed on 4.03.0+flambda fails

### ISSUE THREAD

**Issue by nilsbecker** [yoriyuki/Camomile#19]
apparently this is due to some files not being installed by camomile (!). see this issue: https://github.com/ocaml/opam-repository/issues/6305

**Comment by michipili** [comment]
Thank you for reporting this, I'll take a look at this.

**Comment by nilsbecker** [comment]
gentle bump. (i still cannot run utop on 4.03.0+flambda since zed does not install)

**Comment by nilsbecker** [comment]
i was just able to install utop after camomile was updated on opam! thanks a lot!
