### ISSUE TITLE
SEGV while processing zh locale

### ISSUE THREAD

**Issue by rneswold** [yoriyuki/Camomile#47]
I'm on a NetBSD system. Camomile 0.8.6 and 0.8.7 won't build under OPAM's OCaml 4.05 or OCaml 4.06 environments. They all result in a SEGV error. Here's the end of the OPAM `.err` file:

```
camomilelocaledef Camomile/locales/zh.mar
camomilelocaledef Camomile/locales/zh_CN.mar
camomilelocaledef Camomile/locales/zh_HK.mar
camomilelocaledef Camomile/locales/zh_MO.mar
camomilelocaledef Camomile/locales/zh_SG.mar
camomilelocaledef Camomile/locales/zh_TW.mar
camomilelocaledef Camomile/locales/zh_TW_STROKE.mar
camomilelocaledef Camomile/locales/zh__PINYIN.mar (got signal SEGV)
(cd _build/default/Camomile && ./tools/camomilelocaledef.exe --file locales/zh__PINYIN.txt locales)
```

Unfortunately the stack trace isn't too enlightening:

```
Program terminated with signal 11, Segmentation fault.
#0  0x000000000059eb2b in caml_c_call ()
(gdb)
```

Any other info I can provide to get this fixed? (I can't install `utop` until this builds.)

**Comment by yoriyuki** [comment]
Easy fix is to remove zh__PINYIN.txt  Another solution could be to increase the stack size.

**Comment by rneswold** [comment]
Cranked the stack size up and it worked. Thanks!
