### ISSUE TITLE
Proposal: Use topkg for releases.

### ISSUE THREAD

**Issue by rgrinberg** [yoriyuki/Camomile#62]
Using [topkg](https://github.com/dbuenzli/topkg/) along with [opam-publish](https://github.com/ocaml/opam-publish) to create releases. This has the following advantages:

* Automated process for making and submitting our own releases
* We'll be creating and uploading our own tarballs. Github sometimes likes to change the checksums of their archives. [example](https://github.com/ocaml/opam-repository/pull/11619#issuecomment-374982904)
* Our releases will include the CHANGELOG from the previous release. [example](https://github.com/ocaml/opam-repository/pull/11629)

I can set this up and add some small instructions for how to make a release using topkg.

**Comment by yoriyuki** [comment]
Sure, go for it.

**Comment by yoriyuki** [comment]
Camomile 1.0.0 is released and successfully merged to opam https://github.com/ocaml/opam-repository/commit/820cd1990b6bfa8530696187ee356b39effa11b0
