### ISSUE TITLE
Makefile is sensitive to number of parallel jobs

### ISSUE THREAD

**Issue by SethTisue** [yoriyuki/Camomile#9]
`opam install camomile` was failing for me on Mac OS X 10.9: https://gist.github.com/SethTisue/f99fcb80ffa639951d18

where the key lines are:

```
# File "internal/uReStrLexer.mll", line 37, characters 0-17:
# Error: Unbound module UReStrParser
```

someone else obviously hit the same problem: https://github.com/pld-linux/ocaml-camomile/commit/2ca02a02cad8cf56de82e6bcdbe0f72049a7cc34)

I was able to work around it with `MAKEFLAGS=-j1 opam install camomile`, but it would be nice if the underlying issue were addressed.

**Comment by yoriyuki** [comment]
Does anyone still experience this problem after we moved to jbuilder?

**Comment by SethTisue** [comment]
I tried `brew install opam` followed by `opam install utop` just now on my OS X 10.13 machine and it succeeded no problem.

**Comment by yoriyuki** [comment]
Thank you!
